/*******************************************************************

EVEN FIBONACCI NUMBERS

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

********************************************************************/

function fibonacciNumbers(limit = 4000000, startNumber1 = 1, startNumber2 = 2){
    let firstNumber = startNumber1;
    let secondNumber = startNumber2;
    let thirdNumber = firstNumber + secondNumber;
    let counter = (firstNumber % 2 == 0 ? firstNumber : 0) + (secondNumber % 2 == 0 ? secondNumber : 0)
    while (thirdNumber < limit){
        if (thirdNumber % 2 == 0){
            counter += thirdNumber;
        }
        firstNumber = secondNumber;
        secondNumber = thirdNumber;
        thirdNumber = firstNumber + secondNumber;
    }
    return counter
}

module.exports = fibonacciNumbers;